title: Sonal Gupta
logo: /assets/img/logo.png
description: I am an industry professional with 2+ year of exxperience.I am an aspiring machine learnng engineer
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
